### ISSUE TITLE
Wallet failing to spend after accepting a transfer that was collaboratively built by two wallets

### ISSUE THREAD

**Issue by St333p** [RGB-WG/rgb-std#253]
I'm trying to build a collaborative RGB transfer in which more than one wallet contribute inputs. The receiving wallet happily accepts the transfer but then it's not able to spend from the resulting allocation(s) with error: `Completion(Stock("the provided state transition is not a part of the bundle"))`

Here you can find the test that reproduces this issue (run `cargo test --test transfers collaborative_transfer`): https://github.com/St333p/rgb-integration-tests/tree/rgb_coinjoin

Note: this should be tested on rust 1.79 due to https://github.com/rust-amplify/amplify-derive/issues/44

**Comment by dr-orlovsky** [comment]
Further investigation has shown that this specific case you have reported was caused by the bug. Here is a simple solution, I have already checked that it makes your test to pass: https://github.com/RGB-WG/rgb-std/pull/254

```
running 1 test
test collaborative_transfer has been running for over 60 seconds
test collaborative_transfer ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 75 filtered out; finished in 155.16s
```

However, this was possible due to the fact that the first participant hasn't concealed his state transition and the second one was able to extract it as a part of his Fascia and add it to the single consignment sent to the receiver.

What this mean that the actual problem related to the multi-peer PSBT-based protocols is theoretically still there, it is just that the test you have doesn't reveal it yet. This problem can't be solved at RGB level and requires a protocols on top (for instance, RGB with Lightning BOLT solves this problem for the case of BOLT channels, since both parties can deterministically generate state transitions of each other - so for the case of payjoins one needs to design a different protocol, like the one with two consignments etc).

**Comment by St333p** [comment]
Your PR fixes the problem, thanks. I also tried changing the test so that the participants conceal their state transitions and the `accept_transfer` indeed fails, but I see no problems there since the receiving wallet can't be tricked into accepting funds it won't be able to spend.
